name: Publish to Pub/Sub with WIF

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub OIDC token
        id: get-token
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken('sts.googleapis.com');
            require('fs').writeFileSync('.github/workflows/github-token.txt', id_token);

      - name: Build and run Java app
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.github/workflows/github-token.json
        run: |
          ./mvnw clean package
          java -jar target/api-gateway.jar
